### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by Bruno-hsc** [awaw00/autoclose#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Unknown Windows version
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At C:\Users\Bruno\.atom\packages\autoclose\lib\autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didActivatePaneContainer (~/AppData/Local/atom/app-1.27.1/resources/app/src/workspace.js:430:26)
    at Dock.subscriptions.CompositeDisposable.paneContainer.onDidActivatePane (~/AppData/Local/atom/app-1.27.1/resources/app/src/dock.js:62:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.27.1/resources/app/src/pane-container.js:265:24)
    at Pane.activate (~/AppData/Local/atom/app-1.27.1/resources/app/src/pane.js:1018:46)
    at Pane.focus (~/AppData/Local/atom/app-1.27.1/resources/app/src/pane.js:401:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -1:03.5.0 core:backspace (input.hidden-input)
     -0:58.1.0 core:select-all (input.hidden-input)
     -0:57 core:copy (input.hidden-input)
     -0:48 core:paste (input.hidden-input)
  2x -0:41.8.0 core:backspace (input.hidden-input)
     -0:35.2.0 core:cut (input.hidden-input)
     -0:34 core:backspace (input.hidden-input)
     -0:31.8.0 core:move-left (input.hidden-input)
  2x -0:31.6.0 core:backspace (input.hidden-input)
     -0:27.8.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.2.0 
atom-monokai 0.10.9 
autoclose 0.0.2 
color-picker 2.2.5 
editorconfig 2.2.2 
emmet 2.4.3 
highlight-selected 0.13.1 
monokai 0.24.0 
script 3.17.3 
seti-syntax 1.1.3 
```

**Comment by javaskript** [comment]
This should be resolved with my changes in https://github.com/awaw00/autoclose/pull/16/commits/4f3fe85121d6eceff49cff3cd85d19b2aa84439f

**Comment by shady119** [comment]
i am a new user of atom and github both i am facing the same error in my atom  so what i have to do to fix my error plz anyone figure it out
