### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by r-liciotti** [awaw00/autoclose#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /Users/macbookproretina/.atom/packages/autoclose/lib/autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didActivatePaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:430:26)
    at Dock.subscriptions.CompositeDisposable.paneContainer.onDidActivatePane (/Applications/Atom.app/Contents/Resources/app/src/dock.js:62:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:265:24)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1018:46)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:401:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -9:17.3.0 core:close (input.hidden-input)
  2x -9:16.6.0 pane:show-next-recently-used-item (input.hidden-input)
     -9:16 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -8:04.8.0 core:backspace (input.hidden-input)
     -8:04.4.0 core:save (input.hidden-input)
     -5:07.2.0 pane:show-next-recently-used-item (input.hidden-input)
     -5:06.5.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
  2x -4:53.3.0 core:undo (input.hidden-input)
     -4:52.1.0 core:save (input.hidden-input)
     -2:21.7.0 pane:show-item-1 (input.hidden-input)
  3x -2:19.3.0 core:undo (input.hidden-input)
     -2:15.1.0 core:save (input.hidden-input)
     -0:30.8.0 core:close (input.hidden-input)
 11x -0:29.5.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:26 pane:move-active-item-to-top-of-stack (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-css-class-checker 0.4.3 
atom-ide-ui 0.12.0 
autoclose 0.0.2 
autoclose-html 0.23.0 
busy-signal 1.4.3 
color-picker 2.3.0 
emmet 2.4.3 
html-to-css 0.2.2 
ide-css 0.3.0 
ide-php 0.7.14 
ide-typescript 0.7.6 
intentions 1.1.5 
language-babel 2.85.0 
linter 2.2.0 
linter-ui-default 1.7.1 
open-in-browser 0.5.2 
pigments 0.40.2 
remote-ftp 2.2.0 
zentabs 0.8.9 
```

**Comment by jamesalmeida** [comment]
I keep getting this error too. So often I need to turn off the package. What's going on?

**Comment by javaskript** [comment]
> I keep getting this error too. So often I need to turn off the package. What's going on?

This should be resolved with my changes in https://github.com/awaw00/autoclose/pull/16/commits/4f3fe85121d6eceff49cff3cd85d19b2aa84439f
