### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by withoutwax** [awaw00/autoclose#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /Users/withoutwax/.atom/packages/autoclose/lib/autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:285:26)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:263:18)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1018:46)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:401:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -0:18.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
autoclose 0.0.2 
autoclose-html 0.23.0 
browser-plus 0.0.98 
color-picker 2.3.0 
file-icons 2.1.25 
highlight-selected 0.14.0 
language-babel 2.85.0 
language-haml 0.31.1 
minimap 4.29.9 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
web-view 3.0.0 
```

**Comment by javaskript** [comment]
This should be resolved with my changes in https://github.com/awaw00/autoclose/pull/16/commits/4f3fe85121d6eceff49cff3cd85d19b2aa84439f

**Comment by Airom42** [comment]
This says its been fixed here... but this error just started popping up whenever I open a new file.
**Uncaught TypeError: this.action.disposalAction is not a function**

C:\Users\--\.atom\packages\autoclose\lib\autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (file:///C:/Users/--/.atom/packages/autoclose/lib/autoclose.coffee:39:29)
    at file:///C:/Users/--/.atom/packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (C:\Users\--\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:1172318)
    at Emitter.emit (C:\Users\--\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:1173759)
    at Workspace.didChangeActivePaneItemOnPaneContainer (C:\Users\--\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:424332)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (C:\Users\--\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14:38690)
    at Function.simpleDispatch (C:\Users\--\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:1172318)
    at Emitter.emit (C:\Users\--\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:1173759)
    at PaneContainer.didChangeActiveItemOnPane (C:\Users\--\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:446615)
    at Pane.setActiveItem (C:\Users\--\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:455471)
    at Pane.activateItem (C:\Users\--\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:457641)
    at TabBarView.t.exports.TabBarView.onClick (C:\Users\--\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:1122823)

**Comment by Airom42** [comment]
Removing the package, restarting atom, and redownloading seems to have fixed

**Comment by javaskript** [comment]
@Airom42 The change I suggested fixes the issue, but I don’t believe it has been implemented into the master yet. I submitted a pull request 3 months ago, but the change wasn’t applied to the release. Glad to hear it’s working for you now, though.
