### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by gastrodon** [awaw00/autoclose#22]
Steps to reproduce: 
- Have more than one window open
- Change tabs in any window other than the first

```
TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/home/zero/.atom/packages/autoclose/lib/autoclose.coffee:39:29)
    at /home/zero/.atom/packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at Workspace.didActivatePaneContainer (/usr/lib/atom/src/workspace.js:503:20)
    at Dock.subscriptions.CompositeDisposable.paneContainer.onDidActivatePane (/usr/lib/atom/src/dock.js:66:14)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at PaneContainer.didActivatePane (/usr/lib/atom/src/pane-container.js:313:18)
    at Pane.activate (/usr/lib/atom/src/pane.js:1112:40)
    at Pane.focus (/usr/lib/atom/src/pane.js:416:17)
    at HTMLElement.handleFocus (/usr/lib/atom/src/pane-element.js:41:20)
```

This has been a known issue for a _long_ time. Why is it still going on?

**Comment by pretraket** [comment]
Driving me insane, close to just switching to another program just because this problem isnt getting solved ever

**Comment by Optica1** [comment]
1. Close all open files 
2. Open a file
3. Error keeps popping up on different action. This is solved after restarting Atom.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 19.04
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2


### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /home/tom/.atom/packages/autoclose/lib/autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at Workspace.didActivatePaneContainer (/usr/share/atom/resources/app/static/<embedded>:11:424073)
    at WorkspaceCenter.paneContainer.onDidActivatePane (/usr/share/atom/resources/app/static/<embedded>:14:44249)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at PaneContainer.didActivatePane (/usr/share/atom/resources/app/static/<embedded>:11:446309)
    at Pane.activate (/usr/share/atom/resources/app/static/<embedded>:11:463632)
    at Pane.focus (/usr/share/atom/resources/app/static/<embedded>:11:455075)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-folding 0.0.9 
autoclose 0.0.2 
folding-markdown 0.1.4 
highlight-selected 0.16.0 
language-markdown 0.37.0 
markdown-folding 0.3.1 
markdown-image-paste 2.5.2 
markdown-pdf 2.2.0 
markdown-toc-auto 0.14.0 
markdown-writer 2.11.7 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
theme-switcher 1.1.0 
todo-show 2.3.2 
```

**Comment by BrunoSeriese** [comment]
From what i see, i reccomend using Emmet instead seeing how it has similar functionality without this issue

**Comment by javaskript** [comment]
My changes in https://github.com/awaw00/autoclose/pull/16/commits/4f3fe85121d6eceff49cff3cd85d19b2aa84439f from over a year ago fixed this issue, but it has not been merged into master. This error is simply due to the deprecation of dispoalAction. Just open autoclose.coffee and replace `@action.disposalAction()` with `@action.dispose()`.

**Comment by Wkasel** [comment]
@javaskript why not just fork it, and resubmit, obviously this is abandoned.

**Comment by steve-kg** [comment]
@javaskript Thank you so much buddy
