### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by princessesierra** [awaw00/autoclose#48]
[Enter steps to reproduce:]

1. Opening any file/ tab
2. Switching to any file/ tab 

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At C:\Users\anushka\.atom\packages\autoclose\lib\autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1202941)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:425077)
    at ~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:44778
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1202941)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:447410)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:456254)
    at Pane.activateItem (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:458424)
    at TabBarView.onClick (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1151091)
```

### Commands

```
     -2:52.2.0 intentions:highlight (input.hidden-input)
     -2:52 core:paste (input.hidden-input)
     -2:51.4.0 intentions:highlight (input.hidden-input)
     -2:51.2.0 core:save (input.hidden-input)
     -2:41.5.0 tree-view:copy-full-path (span.name.icon.icon-file-text)
     -2:08.5.0 intentions:highlight (input.hidden-input)
     -2:08.3.0 core:paste (input.hidden-input)
     -2:07.6.0 intentions:highlight (input.hidden-input)
     -2:07.4.0 core:save (input.hidden-input)
     -1:13.4.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -1:11.4.0 core:cancel (input.hidden-input)
     -1:00.1.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:58.5.0 core:confirm (input.hidden-input)
     -0:47.3.0 tree-view:add-file (span.name.icon.icon-file-directory)
  7x -0:45.6.0 core:backspace (input.hidden-input)
     -0:41.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose 0.0.2 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by engwei123** [comment]
how do i get rid of this pop up when 2) switching tabs?

**Comment by Space1230** [comment]
Same bug on MacOS.

[Enter steps to reproduce:]

1. opening a new tab
2. moving a new tab around
3. selecting a new tab

(new tab meaning one without existing data, also happens on existing tabs with data, but not as often I think)

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.3
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2


### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /Users/andysparks/.atom/packages/autoclose/lib/autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1202941)
    at Workspace.didActivatePaneContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:424746)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:469571
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1202941)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:446982)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:464305)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:455748)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -5:35.7.0 tree-view:add-folder (div.tool-panel.tree-view)
  3x -5:27.5.0 core:backspace (input.hidden-input)
     -5:25.5.0 core:confirm (input.hidden-input)
     -5:24.2.0 tree-view:add-file (div.tool-panel.tree-view)
     -5:19.5.0 core:confirm (input.hidden-input)
     -5:07.2.0 tree-view:add-file (div.tool-panel.tree-view)
     -5:02.8.0 core:confirm (input.hidden-input)
     -4:59.9.0 core:backspace (input.hidden-input)
     -4:57.7.0 tree-view:add-file (div.tool-panel.tree-view)
  3x -4:53.1.0 core:backspace (input.hidden-input)
     -4:51.8.0 core:confirm (input.hidden-input)
  2x -2:51.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-codesandbox 0.9.0 
atom-discord 2.0.2 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose 0.0.2 
autocomplete 0.47.0 
autocomplete-javascript 0.0.2 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
hyperclick 0.1.5 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by knoxnethan** [comment]
Having similar issues and when i'm coding it keep appearing. I have also the same packages you got installed.

**Comment by pcachia** [comment]
I had the same problem too for a few days. In the bottom bar click on the red bug icon and then reload packages. It solved the problem for me. Hope this helps.

**Comment by aakatheeri** [comment]
> I had the same problem too for a few days. In the bottom bar click on the red bug icon and then reload packages. It solved the problem for me. Hope this helps.

@pcachia I can not find the red bug icon. The only temporary solution I do is to reload Atom, but after few minutes of opening and closing tabs of files the bug appear again.

**Comment by pcachia** [comment]
@aakatheeri did you try to update all your atom packages?

**Comment by aakatheeri** [comment]
@pcachia Yes, all installed packages are updated. Currently I don't have an issue with it, but it comes between time to time.

**Comment by ericwestphal2014** [comment]
I removed the autoclose package and installed the autoclose-html package, so it still closes html tags but the error went away.

**Comment by pcachia** [comment]
@aakatheeri @ericwestphal2014 thanks for sharing with us.

**Comment by adityanema054** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: 'autoclose' package vundefined


### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At C:\Users\aditya\.atom\packages\autoclose\lib\autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1202941)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:425077)
    at ~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:44778
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1202941)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:447410)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:456254)
    at Pane.activateItem (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:458424)
    at TabBarView.onClick (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1151091)
```

### Commands

```
  2x -9:18.1.0 core:paste (input.hidden-input)
  8x -9:02.2.0 core:backspace (input.hidden-input)
     -8:32.8.0 core:paste (input.hidden-input)
  3x -6:14.9.0 core:backspace (input.hidden-input)
     -1:34.4.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:34.3.0 editor:newline (input.hidden-input)
     -1:26 autocomplete-plus:confirm (input.hidden-input)
     -1:26 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -1:24.5.0 core:move-right (input.hidden-input)
 10x -1:22.4.0 core:backspace (input.hidden-input)
     -0:37.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:37.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -0:35.8.0 core:move-right (input.hidden-input)
  9x -0:34.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.2 
```

**Comment by ChhabriaHeena** [comment]
TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (file:///C:/Users/hp/.atom/packages/autoclose/lib/autoclose.coffee:39:29)
    at file:///C:/Users/hp/.atom/packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (C:\Users\hp\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:1201500)
    at Emitter.emit (C:\Users\hp\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:1202941)
    at Workspace.didActivatePaneContainer (C:\Users\hp\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:424746)
    at C:\Users\hp\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:469571
    at Function.simpleDispatch (C:\Users\hp\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:1201500)
    at Emitter.emit (C:\Users\hp\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:1202941)
    at PaneContainer.didActivatePane (C:\Users\hp\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:446982)
    at Pane.activate (C:\Users\hp\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:464305)
    at Pane.focus (C:\Users\hp\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:455748)
    at HTMLElement.handleFocus (C:\Users\hp\AppData\Local\atom\app-1.49.0\resources\app.asar\src\pane-element.js:41:20)

**Comment by Dans7an** [comment]
I just closed the Atom application, then reopened it and the message disappeared.

**Comment by Samantasoumyadip** [comment]
Thanks @ericwestphal2014  your suggestion worked😊😊

**Comment by Memphis1983** [comment]
Yes as Dans7an mentioned above, I closed Atom and opened, the error/bug disappeared and it's not showing up again. thanks mate
