### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by jeirbeir** [awaw00/autoclose#51]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.13.6
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /Users/JeriW/.atom/packages/autoclose/lib/autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190202)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191643)
    at Workspace.didActivatePaneContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:424745)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:469570
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190202)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191643)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:446981)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:464304)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:455747)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
  6x -4:04.1.0 core:backspace (input.hidden-input)
     -3:59.4.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -3:59.4.0 editor:newline (input.hidden-input)
     -3:58.9.0 core:move-up (input.hidden-input)
  2x -3:58.2.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
  5x -3:50.2.0 core:backspace (input.hidden-input)
     -3:44.7.0 core:move-right (input.hidden-input)
  5x -3:43.6.0 core:backspace (input.hidden-input)
     -3:36.8.0 core:move-right (input.hidden-input)
  2x -3:35.4.0 core:backspace (input.hidden-input)
  6x -3:32.9.0 core:move-right (input.hidden-input)
  6x -3:31.4.0 core:backspace (input.hidden-input)
     -3:28.4.0 core:save (input.hidden-input)
     -2:15.7.0 core:save-as (input.hidden-input)
  2x -1:11.4.0 core:save (input.hidden-input)
     -0:45.2.0 core:save-as (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose 0.0.2 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
linter-eslint 8.5.5 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by alfonsosaera** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.5
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2


### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /home/alfonso/.atom/packages/autoclose/lib/autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1213350)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/share/atom/resources/app/static/<embedded>:11:424688)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (/usr/share/atom/resources/app/static/<embedded>:14:44396)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1213350)
    at PaneContainer.didChangeActiveItemOnPane (/usr/share/atom/resources/app/static/<embedded>:11:447021)
    at PaneContainer.didActivatePane (/usr/share/atom/resources/app/static/<embedded>:11:446498)
    at Pane.activate (/usr/share/atom/resources/app/static/<embedded>:11:463916)
    at Pane.focus (/usr/share/atom/resources/app/static/<embedded>:11:455359)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -3:14.1.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose 0.0.2 
autoclose-html 0.23.0 
build 0.70.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
hyperclick 0.1.5 
ide-json 0.2.1 
intentions 1.1.5 
language-babel 2.85.0 
language-ejs 0.4.0 
language-sql-mysql 0.3.1 
latex 0.50.2 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
minimap 4.29.9 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
```

**Comment by jalbreht** [comment]
Hi there,

I have the same notification showing up as above, but am not sure what your instructions mean as I am not familiar with the terminology. Would you be able to give me a suggestion on how to proceed? Many thanks

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2


### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At C:\Users\Jerne\.atom\packages\autoclose\lib\autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1190297)
    at Emitter.emit (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1191738)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:425171)
    at ~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:44778
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1190297)
    at Emitter.emit (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1191738)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:447504)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:456348)
    at Pane.activateItem (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:458518)
    at TabBarView.onClick (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1139888)
```

### Commands

```
     -2:37.4.0 core:backspace (input.hidden-input)
     -2:34.8.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose 0.0.2 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```
