### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by vinuka13** [awaw00/autoclose#63]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At C:\Users\acer\.atom\packages\autoclose\lib\autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1191492)
    at Workspace.didActivatePaneContainer (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:425325)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:44631
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1191492)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:447561)
    at Pane.activate (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:464884)
    at Pane.focus (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:456327)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -6:44.8.0 core:backspace (input.hidden-input)
     -6:33.7.0 tree-view:copy-full-path (li.file.entry.list-item.selected)
     -6:29.7.0 core:paste (span.syntax--punctuation.syntax--definition.syntax--string.syntax--begin.syntax--html)
     -6:28.3.0 core:save (input.hidden-input)
     -4:35.9.0 core:copy (input.hidden-input)
     -4:34.8.0 core:backspace (input.hidden-input)
     -4:23.8.0 core:save (input.hidden-input)
     -3:25.7.0 core:backspace (input.hidden-input)
     -3:24.7.0 core:save (input.hidden-input)
     -1:38.1.0 core:paste (input.hidden-input)
 36x -1:36.6.0 core:backspace (input.hidden-input)
     -1:20.3.0 tree-view:copy-full-path (li.file.entry.list-item.selected)
     -1:17.6.0 core:paste (input.hidden-input)
     -1:16.1.0 core:save (input.hidden-input)
     -0:13.2.0 core:backspace (input.hidden-input)
     -0:11.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose 0.0.2 
csslint 1.2.0 
emmet 2.4.3 
hyperclick 0.1.5 
language-ejs 0.4.0 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by suriyakumar5967** [comment]
> [Enter steps to reproduce:]
> 
> 1. ...
> 2. ...
> 
> **Atom**: 1.53.0 x64
> **Electron**: 6.1.12
> **OS**: Microsoft Windows 10 Home Single Language
> **Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2
> 
> ### Stack Trace
> Uncaught TypeError: this.action.disposalAction is not a function
> 
> ```
> At C:\Users\acer\.atom\packages\autoclose\lib\autoclose.coffee:39
> 
> TypeError: this.action.disposalAction is not a function
>     at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
>     at /packages/autoclose/lib/autoclose.coffee:26:8
>     at Function.simpleDispatch (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1190051)
>     at Emitter.emit (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1191492)
>     at Workspace.didActivatePaneContainer (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:425325)
>     at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:44631
>     at Function.simpleDispatch (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1190051)
>     at Emitter.emit (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1191492)
>     at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:447561)
>     at Pane.activate (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:464884)
>     at Pane.focus (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:456327)
>     at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
> ```
> 
> ### Commands
> ```
>      -6:44.8.0 core:backspace (input.hidden-input)
>      -6:33.7.0 tree-view:copy-full-path (li.file.entry.list-item.selected)
>      -6:29.7.0 core:paste (span.syntax--punctuation.syntax--definition.syntax--string.syntax--begin.syntax--html)
>      -6:28.3.0 core:save (input.hidden-input)
>      -4:35.9.0 core:copy (input.hidden-input)
>      -4:34.8.0 core:backspace (input.hidden-input)
>      -4:23.8.0 core:save (input.hidden-input)
>      -3:25.7.0 core:backspace (input.hidden-input)
>      -3:24.7.0 core:save (input.hidden-input)
>      -1:38.1.0 core:paste (input.hidden-input)
>  36x -1:36.6.0 core:backspace (input.hidden-input)
>      -1:20.3.0 tree-view:copy-full-path (li.file.entry.list-item.selected)
>      -1:17.6.0 core:paste (input.hidden-input)
>      -1:16.1.0 core:save (input.hidden-input)
>      -0:13.2.0 core:backspace (input.hidden-input)
>      -0:11.8.0 core:save (input.hidden-input)
> ```
> 
> ### Non-Core Packages
> ```
> atom-beautify 0.33.4 
> atom-html-preview 0.2.6 
> atom-ternjs 0.20.0 
> autoclose 0.0.2 
> csslint 1.2.0 
> emmet 2.4.3 
> hyperclick 0.1.5 
> language-ejs 0.4.0 
> pigments 0.40.6 
> Sublime-Style-Column-Selection 1.7.5 
> ```

**Comment by PortoAgustin** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2


### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At C:\Users\agust\.atom\packages\autoclose\lib\autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1182710)
    at Emitter.emit (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1184151)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:427239)
    at ~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:44736
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1182710)
    at Emitter.emit (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1184151)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:449569)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:458413)
    at Pane.activateItem (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:460583)
    at TabBarView.onClick (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1133631)
```

### Commands

```
     -2:49 core:backspace (input.hidden-input)
     -2:48.2.0 autocomplete-plus:confirm (input.hidden-input)
     -2:47.8.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -2:47.8.0 editor:newline (input.hidden-input)
  3x -2:47 core:backspace (input.hidden-input)
     -2:21.9.0 autocomplete-plus:confirm (input.hidden-input)
     -2:21.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:52 core:paste (input.hidden-input)
  2x -1:47.9.0 core:backspace (input.hidden-input)
     -1:32.5.0 core:save (input.hidden-input)
     -1:17.3.0 core:move-down (input.hidden-input)
     -1:15.9.0 core:move-up (input.hidden-input)
     -1:14.9.0 core:move-right (input.hidden-input)
  3x -1:14.4.0 core:backspace (input.hidden-input)
     -0:43.9.0 atom-beautify:beautify-editor (input.hidden-input)
  2x -0:20.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose 0.0.2 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.6 
```

**Comment by llggyy233** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2


### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At C:\Users\71407\.atom\packages\autoclose\lib\autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at Workspace.didActivatePaneContainer (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:427383)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:472205
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:449616)
    at Pane.activate (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:466939)
    at Pane.focus (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:458382)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -6:46.3.0 intentions:highlight (input.hidden-input)
     -6:46.1.0 core:paste (input.hidden-input)
     -6:43.8.0 core:move-left (input.hidden-input)
     -6:37.2.0 intentions:highlight (input.hidden-input)
     -6:37 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
autoclose 0.0.2 
autocomplete-paths 2.15.2 
busy-signal 2.0.1 
docblockr 0.13.7 
emmet 2.4.3 
git-plus 8.7.1 
intentions 1.1.5 
language-vue 0.26.0 
language-vue-component 0.5.0 
linter 3.3.1 
linter-eslint 8.6.6 
linter-ui-default 3.3.1 
minimap 4.39.14 
open-in-browsers 0.0.30 
prettier-atom 0.60.1 
simplified-chinese-menu 5.3.5 
```
