### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by Olabusiyi** [awaw00/autoclose#64]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.2.3
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /Users/ola/.atom/packages/autoclose/lib/autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (/private/var/folders/k3/b55sk9xj05l4hjl58v2bp7g00000gn/T/AppTranslocation/0D2E61BF-CA38-4933-BA27-1A2C8E2709EE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1182710)
    at Emitter.emit (/private/var/folders/k3/b55sk9xj05l4hjl58v2bp7g00000gn/T/AppTranslocation/0D2E61BF-CA38-4933-BA27-1A2C8E2709EE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1184151)
    at Workspace.didActivatePaneContainer (/private/var/folders/k3/b55sk9xj05l4hjl58v2bp7g00000gn/T/AppTranslocation/0D2E61BF-CA38-4933-BA27-1A2C8E2709EE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:426908)
    at /private/var/folders/k3/b55sk9xj05l4hjl58v2bp7g00000gn/T/AppTranslocation/0D2E61BF-CA38-4933-BA27-1A2C8E2709EE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:471730
    at Function.simpleDispatch (/private/var/folders/k3/b55sk9xj05l4hjl58v2bp7g00000gn/T/AppTranslocation/0D2E61BF-CA38-4933-BA27-1A2C8E2709EE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1182710)
    at Emitter.emit (/private/var/folders/k3/b55sk9xj05l4hjl58v2bp7g00000gn/T/AppTranslocation/0D2E61BF-CA38-4933-BA27-1A2C8E2709EE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1184151)
    at PaneContainer.didActivatePane (/private/var/folders/k3/b55sk9xj05l4hjl58v2bp7g00000gn/T/AppTranslocation/0D2E61BF-CA38-4933-BA27-1A2C8E2709EE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:449141)
    at Pane.activate (/private/var/folders/k3/b55sk9xj05l4hjl58v2bp7g00000gn/T/AppTranslocation/0D2E61BF-CA38-4933-BA27-1A2C8E2709EE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:466464)
    at Pane.focus (/private/var/folders/k3/b55sk9xj05l4hjl58v2bp7g00000gn/T/AppTranslocation/0D2E61BF-CA38-4933-BA27-1A2C8E2709EE/d/Atom.app/Contents/Resources/app/static/<embedded>:11:457907)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -1:03.8.0 core:backspace (input.hidden-input)
     -0:55.4.0 core:paste (input.hidden-input)
     -0:54.5.0 core:save (input.hidden-input)
     -0:41.7.0 tree-view:copy-full-path (span.name.icon.icon-file-text)
     -0:26.2.0 tree-view:move (span.name.icon.icon-file-text)
     -0:24.9.0 core:move-left (input.hidden-input)
     -0:24.4.0 core:move-right (input.hidden-input)
     -0:22.8.0 core:confirm (input.hidden-input)
     -0:20.8.0 core:backspace (input.hidden-input)
     -0:19.6.0 core:save (input.hidden-input)
     -0:09.9.0 tree-view:move (span.name.icon.icon-file-text)
     -0:08.4.0 core:move-left (input.hidden-input)
  2x -0:07.7.0 core:move-right (input.hidden-input)
  4x -0:06.5.0 core:backspace (input.hidden-input)
     -0:04.0 core:save (input.hidden-input)
     -0:02.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose 0.0.2 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 3.3.1 
linter-eslint 8.6.6 
linter-ui-default 3.3.1 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by daibeal** [comment]
I've get there same error. Did you manage to solve it?

**Comment by daibeal** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.3.1
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2


### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /Users/daibeal/.atom/packages/autoclose/lib/autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (/private/var/folders/gv/2y3gvr5d1vs150c13j0sjzpc0000gn/T/AppTranslocation/78CA8C7E-797A-4AA7-8C9E-1C1C293FECF7/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/private/var/folders/gv/2y3gvr5d1vs150c13j0sjzpc0000gn/T/AppTranslocation/78CA8C7E-797A-4AA7-8C9E-1C1C293FECF7/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1187631)
    at Workspace.didActivatePaneContainer (/private/var/folders/gv/2y3gvr5d1vs150c13j0sjzpc0000gn/T/AppTranslocation/78CA8C7E-797A-4AA7-8C9E-1C1C293FECF7/d/Atom.app/Contents/Resources/app/static/<embedded>:11:427383)
    at /private/var/folders/gv/2y3gvr5d1vs150c13j0sjzpc0000gn/T/AppTranslocation/78CA8C7E-797A-4AA7-8C9E-1C1C293FECF7/d/Atom.app/Contents/Resources/app/static/<embedded>:11:472205
    at Function.simpleDispatch (/private/var/folders/gv/2y3gvr5d1vs150c13j0sjzpc0000gn/T/AppTranslocation/78CA8C7E-797A-4AA7-8C9E-1C1C293FECF7/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/private/var/folders/gv/2y3gvr5d1vs150c13j0sjzpc0000gn/T/AppTranslocation/78CA8C7E-797A-4AA7-8C9E-1C1C293FECF7/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1187631)
    at PaneContainer.didActivatePane (/private/var/folders/gv/2y3gvr5d1vs150c13j0sjzpc0000gn/T/AppTranslocation/78CA8C7E-797A-4AA7-8C9E-1C1C293FECF7/d/Atom.app/Contents/Resources/app/static/<embedded>:11:449616)
    at Pane.activate (/private/var/folders/gv/2y3gvr5d1vs150c13j0sjzpc0000gn/T/AppTranslocation/78CA8C7E-797A-4AA7-8C9E-1C1C293FECF7/d/Atom.app/Contents/Resources/app/static/<embedded>:11:466939)
    at Pane.focus (/private/var/folders/gv/2y3gvr5d1vs150c13j0sjzpc0000gn/T/AppTranslocation/78CA8C7E-797A-4AA7-8C9E-1C1C293FECF7/d/Atom.app/Contents/Resources/app/static/<embedded>:11:458382)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
  7x -4:04.3.0 core:close (atom-pane.pane.active)
     -2:55.9.0 atom-live-server:startServer (input.hidden-input)
     -2:45.2.0 editor:select-to-end-of-line (input.hidden-input)
     -2:43.5.0 core:paste (input.hidden-input)
     -2:36.7.0 core:save (input.hidden-input)
     -2:25 editor:select-to-end-of-line (input.hidden-input)
     -2:24 core:paste (input.hidden-input)
     -2:21.8.0 core:save (input.hidden-input)
     -1:59.5.0 editor:select-to-end-of-line (input.hidden-input)
     -1:58.3.0 core:paste (input.hidden-input)
  4x -1:57.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
atom-ternjs 0.20.0 
autoclose 0.0.2 
csslint 1.2.0 
emmet 2.4.3 
hyperclick 0.1.5 
language-ejs 0.4.0 
livereload 0.4.4 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by ruslanrajabov** [comment]
Hi there, i have same issue, what to do? how to fix it?

**Comment by nitisharisetty** [comment]
> I've get there same error. Did you manage to solve it?

no man

**Comment by MaguedAlaghbary** [comment]
Hi I am facing the same issue too.

**Comment by smnhfr** [comment]
Hey, I become the same error, did someone solve it?

**Comment by adarsxh** [comment]
What is this issue? How to solve it?

**Comment by Rajasekarmech24** [comment]
Same issue. How to fix it

**Comment by Pallavi2920** [comment]
same issue.

**Comment by PooneJabbari** [comment]
same here! somebody help!

**Comment by vamsykrishna1996** [comment]
here too..

**Comment by Japanmavani** [comment]
I same same issue please tell ho to solve it

**Comment by ShantyLifecoach** [comment]
How do I solve this issue please

**Comment by scifithedev** [comment]
Doesn't look like we will get help anytime soon

**Comment by killmonger-112** [comment]
please give a solution for this

**Comment by sujithrajs** [comment]
Scroll down to find the autoclose package listed under Packages, or type “autoclose” into the search box. Click the Disable button. or uninstall it.
