### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by Pratik-Singh-web** [awaw00/autoclose#81]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [autoclose](https://github.com/awaw00/autoclose) package 0.0.2

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At C:\Users\Lenovo\.atom\packages\autoclose\lib\autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose/lib/autoclose.coffee:39:29)
    at /packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
    at Workspace.didActivatePaneContainer (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:427498)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:44851
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:449731)
    at Pane.activate (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:467054)
    at Pane.focus (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:458497)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -0:16.4.0 tree-view:remove (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose 0.0.2 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.6 
```

**Comment by mshabazi68** [comment]
Same issue!

**Comment by MrTipz** [comment]
same issue

**Comment by Davheed2** [comment]
same issue

**Comment by LauraBizzle** [comment]
Same issue, happens quite frequently

**Comment by jtr13** [comment]
Same, will have to uninstall b/c I can't with this error popping up all the time.

```
TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/Users/joycerobbins/.atom/packages/autoclose/lib/autoclose.coffee:39:29)
    at /Users/joycerobbins/.atom/packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188366)
    at Workspace.didActivatePaneContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:427498)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:472320
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188366)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:449731)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:467054)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:458497)
    at HTMLElement.handleFocus (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:41:20)
```

**Comment by CDE-ID** [comment]
Has anybody found a solution? and if not, any replacement packages that are recommended?

**Comment by jtr13** [comment]
@CDE-ID `autoclose-html-plus` seems to work. If you search for `autoclose-html` in the Install Packages search box, a lot of options pop up.

**Comment by Anand52** [comment]
same issue i have

**Comment by pawnd4** [comment]
TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (file:///C:/Users/nagato/.atom/packages/autoclose/lib/autoclose.coffee:39:29)
    at file:///C:/Users/nagato/.atom/packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (C:\Users\nagato\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:1187666)
    at Emitter.emit (C:\Users\nagato\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:1189107)
    at Workspace.didChangeActivePaneItemOnPaneContainer (C:\Users\nagato\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:428429)
    at C:\Users\nagato\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:14:45152
    at Function.simpleDispatch (C:\Users\nagato\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:1187666)
    at Emitter.emit (C:\Users\nagato\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:1189107)
    at PaneContainer.didChangeActiveItemOnPane (C:\Users\nagato\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:450818)
    at Pane.setActiveItem (C:\Users\nagato\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:459752)
    at Pane.activateItem (C:\Users\nagato\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:461922)
    at TabBarView.onClick (C:\Users\nagato\AppData\Local\atom\app-1.60.0\resources\app\static\<embedded>:11:1138283)

**Comment by PaawanGaba** [comment]
> Has anybody found a solution? and if not, any replacement packages that are recommended?



> @CDE-ID `autoclose-html-plus` seems to work. If you search for `autoclose-html` in the Install Packages search box, a lot of options pop up.

It's not working
